#!/usr/bin/env bash
# Transfer files from client to server
# Accepts 4 param including path, ip, username and SSH private key
if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file="$1"
	ip="$2"
	user="$3"
	private_key="$4"
	scp -o StrictHostKeyChecking=no -i "$private_key" "$file" "$user@$ip":~/;
fi
