#!/usr/bin/env bash
# install nginx on web server
sudo apt-get -y update
sudo apt-get -y install nginx
sed -i "22s/listen .*/listen 80" /etc/nginx/sites-available/default
mkdir -p /var/www/html
chmod -R 755 /var/www
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
