#!/usr/bin/env bash
# install nginx on web server
apt-get -y update
apt-get -y install nginx
mkdir -p /var/www/html
chmod 755 /var/www
ufw allow 'Nginx HTTP'
echo "Hello world!" > /var/www/html/index.html
service nginx start
