#!/usr/bin/env bash
# install nginx on web server
apt-get -y update
apt-get -y install nginx
mkdir -p /var/www/html
chmod 755 /var/www
#ufw allow 'Nginx HTTP'
echo "Hello world!" > /var/www/html/index.html
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default
service nginx start
