#!/usr/bin/env bash
# install nginx and start it
apt-get install nginx

#Firewall setting: allow Nginx to serve HTTP
ufw allow 'Nginx HTTP'

#Create index file over defaukt
echo "Hello World!" >> /var/www/html/index.html

#Give usr perm to site files
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www

#Redirect to /redirect_me to a youtube video
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

#Setup 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sed -i '38i\error_page 404 /error_page.html;' /etc/nginx/sites-available/default

service nginx start
