#!/usr/bin/env bash
# install nginx on web server
# redirect to another site
# include a 404 error 
apt-get -y update
apt-get -y install nginx
# mkdir -p /var/www/html
# chmod 755 /var/www
# ufw allow 'Nginx HTTP'
echo "Hello world!" > /var/www/html/index.html
# error page content
echo "Ceci n'est pas une page" > /var/www/html/404.html
# sed lines
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default
sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/html/; }' /etc/nginx/sites-available/default
service nginx start
