#!/usr/bin/env bash
# install nginx
# configure it to listen on port 80
# configure nginx so that http rresponse contains a header
# header name  mustbe X-served-By
# The hostname must be the value of custom http on runnig nginx server

sudo apt-get -y update
sudo apt-get install -y nginx
sed -i '11i\add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx restart
