#!/usr/bin/env bash
# install nginx
# configure it to listen on port 80
# configure nginx so that http rresponse contains a header
# header name  mustbe X-served-By
# The hostname must be the value of custom http on runnig nginx server

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sed -i "/listen 80 default_server;/a add_header X-Served-By $hostname;" /etc/nginx/sites-available/default
sudo service nginx start
