#!/usr/bin/env bash
# install and configure HAproxy

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

server_config=\
"
frontend web-front
	bind *:80
	mode http
	default_backend web-backd

backend web-backd
	balance roundrobin
	server 19647-web-01 3.237.12.118:80 check
	server 19647-web-02 18.208.132.108:80 check
"
sudo echo "$server_config" | tee -a /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" | tee -a /etc/default/haproxy
sudo service haproxy restart
