#!/usr/bin/env bash
# install and configure HAproxy

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

server_config="\
frontend http-front
	bind *:80
	mode http
	stats uri /haproxy?stats
	default_backend web-servers

backend web-servers
	balance roundrobin
	server 19647-web-01 3.237.12.118:80 check
	server 19647-web-02 18.208.132.108:80 check
"
sudo echo "$server_config" | tee /etc/haproxy/haproxy.cfg
sudo service haproxy start
