#!/usr/bin/env bash
# Transfers file from client to server
# Accepts 4 params including file_path, ip of server
# username scp connects with, private-key_path
if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file="$1"
	ip="$2"
	user="$3"
	private_key="$4"
	scp -o StrictHostKeyChecking=no -i "private_key" "file" "user@ip":~/;
fi
