#!/usr/bin/env bash
# write a manage_my_process script that:
# writes I AM ALIVE! indefinitely to /tmp/my_process
# iterate at a 2 sec pace

path=/var/run/my_process.pid

if [ "$1" = "start" ];then
	./manage_my_process &
	echo "$$" > $path
	echo "manage_my_process started"
elif [ "$1" = "stop" ];then
	pkill -f ./manage_my_process
	rm $path
	echo "manage_my_process stopped"
elif [ "$1" = "restart" ];then
	pkill -f ./manage_my_process
	rm $path
	./manage_my_process &
	echo "$$" > $path
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
