#!/usr/bin/env bash
# write a bash script that displays 1 - 20
# displays 4 and badluck from china on 4th iteration
# displays 9 and bad luck from japan on 9th iteration
# displays 17 and bad luck from italy on 17th iteration
i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
	4)
		echo "bad luck from China";;
	9)
		echo "bad luck from Japan";;
	17)
		echo "bad luck from Italy";;
	esac
	i=$(( i + 1 ))
done
