#!/usr/bin/env bash
# write bash script that displays time 12:59
# display hours from 0 - 12
# display minutes from 1 - 59
m=1
h=0
while [ $h -lt 13 ]
do
	echo "Hour: $h"
	while [ $m -lt 60 ]
	do
		echo "$m"
		m=$(( m + 1 ))
	done
	m=1
	h=$(( h + 1 ))
done
