#!/usr/bin/env bash
#change home IP address
sudo cp /etc/hosts ~/hosts.new
sudo sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/hosts.new
sudo sed -i 's/.*facebook.com//g' ~/hosts.new
sudo sed -i '1 a 8.8.8.8 facebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
